DOMAIN = "meal_vote"
DEFAULT_PEOPLE = "Kind 1,Kind 2,Mama,Papa"
DEFAULT_DATA_PATH = "/share/essenswahl"
CSV_NAME = "dishes.csv"
STORE_KEY = "meal_vote_state"
STORE_VERSION = 1
IMAGE_CACHE_DIR = "meal_vote_images"
SYNC_MINUTES = 2
MAX_IMAGE_BYTES = 8 * 1024 * 1024
